Repository GDSCUTM-CommunityProjects/UBoard, pull requests merged in 2021-11, with the labels that each got.

#23 Fix broken deployment on node:17-alpine
  Dockerfile
Labels: bug

#26 Update `MaterialUI` and fix imports
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Login.tsx
  client/src/components/SignUp.tsx
  client/src/containers/AuthContainer.test.tsx
  client/src/containers/AuthContainer.tsx
  client/yarn.lock
Labels: bug, frontend

#27 Added text and style to the landing page
  client/src/components/Login.tsx
  client/src/components/SignUp.tsx
  client/src/containers/AuthContainer.css
  client/src/containers/AuthContainer.tsx
Labels: frontend

#10 Add routes and UserController + Auth
  .github/workflows/node.js.yml
  Dockerfile
  README.md
  server/controllers/v1/tests/user.test.ts
  server/controllers/v1/user.ts
  server/jest.config.js
  server/middleware/auth.ts
  server/models/index.ts
  server/models/tests/testHelpers.ts
  server/models/user.ts
  server/package.json
  server/routes/v1/index.ts
  server/routes/v1/tests/user.test.ts
  server/routes/v1/user.ts
  server/server.test.ts
  server/server.ts
  server/services/emailService.ts
  server/yarn.lock
Labels: backend

#35 Setup react router in `App.tsx`
  client/package.json
  client/src/App.tsx
  client/yarn.lock
  nginx/conf.d/default.conf.template
Labels: backend

#33 Create CRUD endpoints for posts.
  server/controllers/v1/post.ts
  server/controllers/v1/tests/post.test.ts
  server/middleware/auth.ts
  server/models/tests/testHelpers.ts
  server/routes/v1/index.ts
  server/routes/v1/post.ts
Labels: backend

#34 Created PostDashboard, Header, and Post components
  client/src/App.tsx
  client/src/components/Header.tsx
  client/src/components/Login.tsx
  client/src/components/PostPreview.tsx
  client/src/components/Tags.tsx
  client/src/components/ViewPostDialog.tsx
  client/src/containers/PostDashboard.test.tsx
  client/src/containers/PostDashboard.tsx
Labels: frontend

#28 Upgrade login page design, fix resizing issues
  client/package.json
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/assets/Kaneff_Innovation_Complex_Rotunda.jpg
  client/src/assets/background.jpg
  client/src/components/Login.tsx
  client/src/components/SignUp.tsx
  client/src/containers/AuthContainer.css
  client/src/containers/AuthContainer.test.tsx
  client/src/containers/AuthContainer.tsx
  client/yarn.lock
  server/routes/v1/user.ts
Labels: enhancement, frontend

#31 Creating a new post and implemented a popup preview for the post
  client/src/components/CreatePost.test.tsx
  client/src/components/CreatePost.tsx
  client/src/components/PreviewPopUp.tsx
Labels: frontend

#48 Integrate api with login page
  client/package.json
  client/src/api/v1/index.test.ts
  client/src/api/v1/index.ts
  client/src/components/Login.tsx
  client/src/components/SignIn.tsx
  client/src/components/SignUp.tsx
  client/src/containers/AuthContainer.test.tsx
  client/src/containers/AuthContainer.tsx
  client/yarn.lock
Labels: frontend

#56 Reformat all files with new prettier config
  .prettierrc
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/api/v1/index.test.ts
  client/src/api/v1/index.ts
  client/src/components/CreatePost.test.tsx
  client/src/components/CreatePost.tsx
  client/src/components/Header.tsx
  client/src/components/PostPreview.tsx
  client/src/components/PreviewPopUp.tsx
  client/src/components/SignIn.tsx
  client/src/components/SignUp.tsx
  client/src/components/Tags.tsx
  client/src/components/ViewPostDialog.tsx
  client/src/containers/AuthContainer.css
  client/src/containers/AuthContainer.test.tsx
  client/src/containers/AuthContainer.tsx
  client/src/containers/PostDashboard.test.tsx
  client/src/containers/PostDashboard.tsx
  client/src/containers/index.tsx
  server/controllers/v1/post.ts
  server/controllers/v1/tests/post.test.ts
  server/controllers/v1/tests/user.test.ts
  server/controllers/v1/user.ts
  server/middleware/auth.ts
  server/migrations/20210925190654-create-user.ts
  server/migrations/20210925191009-create-post.ts
  server/migrations/20211001211616-create-comment.ts
  server/models/comment.ts
  server/models/index.ts
  server/models/post.ts
  server/models/tags.ts
  server/models/tests/post.test.ts
  server/models/tests/testHelpers.ts
  server/models/tests/user.test.ts
  server/models/user.ts
  server/routes/v1/post.ts
  server/routes/v1/tests/user.test.ts
  server/routes/v1/user.ts
  server/server.ts
  server/services/emailService.ts
Labels: chore

#55 Add generic typing for client api handler, update related files
  README.md
  client/src/api/v1/index.test.ts
  client/src/api/v1/index.ts
  client/src/components/SignIn.tsx
  client/src/components/SignUp.tsx
  client/src/containers/AuthContainer.test.tsx
Labels: enhancement

#46 Connect dashboard to API
  client/src/App.tsx
  client/src/api/v1/index.ts
  client/src/components/CreatePost.test.tsx
  client/src/components/CreatePost.tsx
  client/src/components/Header.tsx
  client/src/components/PostPreview.tsx
  client/src/components/SignIn.tsx
  client/src/components/ViewPostDialog.tsx
  client/src/containers/AuthContainer.test.tsx
  client/src/containers/AuthContainer.tsx
  client/src/containers/PostDashboard.test.tsx
  client/src/containers/PostDashboard.tsx
  server/controllers/v1/post.ts
  server/controllers/v1/tests/post.test.ts
  server/routes/v1/post.ts
Labels: frontend

#47 Connect CreatePost to API
  client/src/api/v1/index.ts
  client/src/components/CreatePost.test.tsx
  client/src/components/CreatePost.tsx
Labels: frontend

#66 Reformat all files with new prettier config
  .prettierrc
  client/src/App.test.tsx
  client/src/components/PostPreview.tsx
  client/src/components/SignIn.tsx
  client/src/components/SignUp.tsx
  client/src/components/Tags.tsx
  client/src/containers/AuthContainer.css
  client/src/containers/AuthContainer.test.tsx
  client/src/containers/AuthContainer.tsx
  client/src/containers/PostDashboard.test.tsx
  client/src/containers/PostDashboard.tsx
  client/src/containers/index.tsx
  server/controllers/v1/tests/user.test.ts
  server/controllers/v1/user.ts
  server/jest.config.js
  server/middleware/auth.ts
  server/migrations/20210925190654-create-user.ts
  server/migrations/20210925191009-create-post.ts
  server/migrations/20211001211616-create-comment.ts
  server/models/comment.ts
  server/models/index.ts
  server/models/post.ts
  server/models/tags.ts
  server/models/tests/post.test.ts
  server/models/tests/testHelpers.ts
  server/models/tests/user.test.ts
  server/models/user.ts
  server/routes/v1/tests/user.test.ts
  server/routes/v1/user.ts
  server/server.ts
  server/services/emailService.ts
Labels: chore
