Repository GDSCUTM-CommunityProjects/UBoard, pull requests merged in 2021-12, with the labels that each got.

#67 Implement Tags on frontend & backend
  client/src/api/v1/index.ts
  client/src/components/CreatePost.test.tsx
  client/src/components/CreatePost.tsx
  client/src/components/PostPreview.tsx
  client/src/components/PreviewPopUp.tsx
  client/src/components/Tags.tsx
  client/src/containers/PostDashboard.test.tsx
  server/controllers/v1/post.ts
  server/controllers/v1/tests/post.test.ts
  server/models/PostTags.ts
  server/models/post.ts
  server/models/tags.ts
  server/models/tests/post.test.ts
  server/models/tests/testHelpers.ts
  server/routes/v1/post.ts
Labels: backend, frontend

#73 Style adjustment to tags
  client/src/components/CreatePost.test.tsx
  client/src/components/CreatePost.tsx
  client/src/components/Tags.tsx
Labels: enhancement, frontend

#76 Update backend to implement map coordinates
  server/controllers/v1/post.ts
  server/controllers/v1/tests/post.test.ts
  server/migrations/20210925191009-create-post.ts
  server/models/post.ts
  server/models/tests/post.test.ts
  server/models/tests/testHelpers.ts
  server/routes/v1/post.ts
Labels: backend

#72 Front-End Google Maps Integration
  client/package.json
  client/src/App.tsx
  client/src/components/CreatePost.test.tsx
  client/src/components/CreatePost.tsx
  client/src/components/LocationMap.tsx
  client/src/components/PreviewPopUp.tsx
  client/src/components/ViewPostDialog.tsx
  client/yarn.lock
Labels: frontend

#77 Implement post-editing
  client/src/api/v1/index.ts
  client/src/components/LocationMap.tsx
  client/src/components/ViewPostDialog.tsx
Labels: frontend

#68 Implement search functionality for dashboard
  README.md
  client/src/api/v1/index.ts
  client/src/components/Header.tsx
  client/src/containers/PostDashboard.tsx
  server/controllers/v1/post.ts
  server/routes/v1/post.ts
Labels: backend, frontend

#70 Create CRUD endpoints for comments.
  client/src/api/v1/index.ts
  server/controllers/v1/comment.ts
  server/controllers/v1/post.ts
  server/controllers/v1/tests/comment.test.ts
  server/migrations/20211001211616-create-comment.ts
  server/models/comment.ts
  server/models/post.ts
  server/models/tests/testHelpers.ts
  server/routes/v1/comment.ts
  server/routes/v1/index.ts
Labels: backend

#96 Change PostPreview Style
  client/src/components/PostPreview.tsx
  client/src/components/Tags.tsx
  client/src/containers/PostDashboard.test.tsx
  client/src/containers/PostDashboard.tsx
Labels: enhancement, frontend
