Repository GDSCUTM-CommunityProjects/UBoard, pull requests merged in 2021-10, with the labels that each got.

#4 Created a login and sign up component
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/assets/background.jpg
  client/src/components/Login.tsx
  client/src/components/SignUp.tsx
  client/src/containers/AuthContainer.css
  client/src/containers/AuthContainer.test.tsx
  client/src/containers/AuthContainer.tsx
  client/src/containers/index.tsx
  client/src/logo.svg
  client/yarn.lock
Labels: frontend

#22 Set up NGINX reverse proxy
  nginx/conf.d/default.conf.template
Labels: bug

#21 Implement userRoute (password reset & confirmation)
  server/routes/v1/index.ts
  server/routes/v1/user.ts
  server/server.ts
Labels: backend
