Repository GDSCUTM-CommunityProjects/UBoard, pull requests merged in 2022-01, with the labels that each got.

#105 Fix polling and interactions
  client/src/components/CreatePost.test.tsx
  client/src/components/CreatePost.tsx
  client/src/components/ViewPostDialog.tsx
  client/src/containers/AuthContainer.tsx
  client/src/containers/PostDashboard.tsx
  server/models/userPostLikes.ts
  server/models/usercheckin.ts
  server/routes/v1/post.ts
  server/routes/v1/user.ts
Labels: bug, backend, frontend

#97 Add post type variations
  client/src/api/v1/index.ts
  client/src/components/CreatePost.test.tsx
  client/src/components/CreatePost.tsx
  client/src/components/PostPreview.tsx
  client/src/components/PreviewPopUp.tsx
  client/src/components/ViewPostDialog.tsx
  client/src/components/constants/postTypes.ts
  client/src/containers/PostDashboard.test.tsx
  client/src/containers/PostDashboard.tsx
  server/controllers/v1/post.ts
  server/controllers/v1/tests/post.test.ts
  server/models/post.ts
  server/models/tests/testHelpers.ts
  server/routes/v1/post.ts
Labels: backend, frontend

#102 Implement map view on dashboard
  client/src/api/v1/index.ts
  client/src/assets/blue-marker.png
  client/src/assets/green-marker.png
  client/src/assets/red-marker.png
  client/src/components/LocationMap.tsx
  client/src/containers/PostDashboard.tsx
  server/controllers/v1/post.ts
  server/routes/v1/post.ts
Labels: enhancement, frontend

#98 Integrate comments into frontend
  client/src/api/v1/index.ts
  client/src/components/PostComment.tsx
  client/src/components/ViewPostDialog.tsx
  server/controllers/v1/comment.ts
Labels: frontend
